### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by chr1st1ank** [MephistoXoL/Docker-WebDav_Sync#1]
Hi @MephistoXoL,
Thank you very much for this simple yet effective solution for syncing.
I have a quick question: what license is this repository under?

**Comment by MephistoXoL** [comment]
Hi @chr1st1ank.
I've created the License file and update the repo to v1.08

Thanks for your interest!!

**Comment by chr1st1ank** [comment]
Thank you very much for the swift reply. I will update my fork accordingly to GPL.
Maybe I could add some improvements from it here if you like, especially using inode-wait seems more efficient than polling.

**Comment by MephistoXoL** [comment]
Great!
I was testing inotifywait for a while a couple of months ago, but it didn't work properly as I wanted.
e.g.

```
##Monitoring Folders
inotifywait --event create,delete --monitor --recursive --quiet --format '%e - %w%f' /Folder_Remote/ /Folder_Local/ | while read -r event; do echo "$event" && /usr/bin/Sync_Folders.sh; done
```

Dont notify when I upload files from Nextcloud.

Feel free to improve it.
